server:
  port: 8083
spring:
  application:
    name: notification-service
  # Mail
  #https://mailtrap.io/
  #log in with github and use the test inbox in email testing section
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 109b47d8dc8a18
    password: 4387d8bd42fdc9
    protocol: smtp
  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema:
          registry:
            url: http://127.0.0.1:8085
        specific:
          avro:
            reader: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: notification-service
  tracing:
    sampling:
      probability: 1.0

loki:
  url: http://localhost:3100/loki/api/v1/push
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer
