version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data/mongodb:/data/db
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8085:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: broker:29092
      #      KAFKA_CLUSTERS_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql
  loki:
    image: grafana/loki:main
    command: [ '-config.file=/etc/loki/local-config.yaml' ]
    ports:
      - '3100:3100'
  prometheus:
    image: prom/prometheus:v2.46.0
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
  tempo:
    image: grafana/tempo:2.2.2
    command: [ '-config.file=/etc/tempo.yaml' ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - '3110:3100' # Tempo
      - '9411:9411' # zipkin
  grafana:
    image: grafana/grafana:10.1.0
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - '3000:3000'


# http://localhost:9000/swagger-ui.html when API is UP too
# https://kind.sigs.k8s.io/
# install go and kubectl there

# open localhost:8086
# kafka ui
# configure a cluster
# cluster name:      localhost
# bootstrap servers: broker
# port:              29092
# validate and submit

# open http://localhost:3000/
# monitoring tracing and logging (grafana)
# open explore
# you have option Loki you can choose and select label 'application'
# go to menu -> dashboards -> new import -> import the json from the blog post

# docker-compose up
# After starting the Keycloak docker container, it's time to set up Keycloak,
# open the URL http://localhost:8181 this should open the home page of keycloak,
# provide admin/admin as the credentials as we have configured it in the docker-compose file.

# In Keycloak, all the clients, users, and roles related to a particular application (or)
# a group of applications reside inside something known as a realm.
# Realms are independent of each other, so if you create one client/user in one realm, you cannot use it from another realm.

# In our project, we will be using the Client Credentials grant,to communicate with the API Gateway and fetch an Access Token,
# and this access token will be verified by the API Gateway against Keycloak.

# To get started, log in to the Keycloak Admin page using the above-mentioned credentials
# and the first thing we are going to do is to create the realm.
# After logging in, click on the dropdown with the text "Keycloak"
# in the top left-side corner and click on the Create Realm button

# Provide the name of the realm(eg: spring-microservices-realm) and click on the Create button
# Now the realm should be created successfully

# Next, click on the Clients link to the left sidebar, and click on Create Client
# Provide any Client ID you like eg: test-client-id and click on Next
# Check Client Authentication as ON

# In the Authentication Flow, select Service accounts roles and unselect all other options,
# this makes sure that our client supports Client Credentials grant
# Click on Next and then Save

# Finally, click on the Credentials tab, here you can view the client secret that is generated automatically
# and you can also regenerate a new client secret.
# Make sure to copy the client secret, we will use this in the later parts to request a token to access the API Gateway

# Realm Settings -> OpenID Endpoint Configuration


#In order to export realm settings so you dont have to do everything again when you redeploy keycloak
#go to http://localhost:8181 -> Realm Settings -> Action -> Partial Export -> include clients and roles
# then click export -> it will create realm.export.json file